# 用物件導向建立stander scaler

## sklearn stander scaler

In [16]:
from sklearn.preprocessing import StandardScaler

In [17]:
data = [[0, 0], [0, 0], [1, 1], [1, 1]]

In [18]:
scaler = StandardScaler()

In [19]:
scaler.fit(data)

StandardScaler(copy=True, with_mean=True, with_std=True)

In [24]:
scaler.mean_

array([ 0.5,  0.5])

In [25]:
scaler.var_

array([ 0.25,  0.25])

In [7]:
scaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [22]:
scaler.transform([[2, 2]])

array([[ 3.,  3.]])

## OOP stander scaler

In [43]:
import numpy as np

In [64]:
class MyStanderScaler:
    def __init__(self):
        self.data_mean_ = None
    
    def fit(self, data):
        self.data_mean_ = np.mean(data, axis=0)
        self.data_std_ = np.std(data, axis=0)
        
    def transform(self, data):
        new_data = (np.array(data)-self.data_mean_)/self.data_std_
        return new_data
    
    def fit_transform(self, data):
        self.fit(data)
        return self.transform(data)
    

In [65]:
myscaler = MyStanderScaler()

In [67]:
myscaler.fit(data)

In [68]:
myscaler.data_mean_

array([ 0.5,  0.5])

In [69]:
myscaler.data_std_

array([ 0.5,  0.5])

In [70]:
myscaler.transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [71]:
myscaler_new = MyStanderScaler()

In [72]:
myscaler_new.fit_transform(data)

array([[-1., -1.],
       [-1., -1.],
       [ 1.,  1.],
       [ 1.,  1.]])